### ISSUE TITLE
Add a Fake PKG label [Feature Request]

### ISSUE THREAD

**Issue by ccfman2004** [hippie68/pkgrename#11]
Would it be possible to have this app add an FPKG label if the PKG is an fPKG as a label parameter?

**Comment by hippie68** [comment]
Yes, it is possible. I am going to implement this.

**Comment by hippie68** [comment]
Thank you for the feature suggestion. I have implemented this feature and updated the source code. The compilation process has changed a little - see notes in the latest commit. If you want to use the feature right now, you can compile and run the program on Linux or in WSL. Releasing a new Windows version may take a while due to limited spare time.

**Comment by hippie68** [comment]
An untested Windows version that has this feature is now available: https://github.com/hippie68/pkgrename/releases/tag/v1.09-beta

**Comment by ccfman2004** [comment]
Sorry it took so long to get back to you. The beta build seems to work just fine. Thank you.
